"""
Shared pytest fixtures for backend tests.

Key fixture:
- mock_jwks: patches fetch_jwks() so auth tests work without a live
  frontend. Automatically applied to all tests in this directory.
  Tests that override get_current_user entirely (test_tasks.py) are
  unaffected because dependency_overrides replaces the whole function.
"""

from unittest.mock import AsyncMock, patch

import pytest

from tests.fixtures.jwt_tokens import get_test_jwks


@pytest.fixture(autouse=True)
def mock_jwks():
    """
    Patch fetch_jwks() to return the test JWKS for every test.

    This prevents auth tests from making real HTTP calls to the
    frontend JWKS endpoint. The test JWKS contains the Ed25519 public
    key that matches tokens generated by create_test_jwt().

    Safe for test_tasks.py: those tests override get_current_user
    entirely via app.dependency_overrides, so fetch_jwks is never
    called at all — this patch is a no-op for them.
    """
    with patch(
        "dependencies.fetch_jwks",
        new_callable=AsyncMock,
        return_value=get_test_jwks(),
    ):
        yield
